import type { Metadata } from "next";
import person from "_assets/images/person.png";
import Image from "next/image";
import tw from "tailwind-styled-components";
import { author } from "_appData";
import { Params } from "_types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Params;
export default function HomePage(props: Props) {
  const { params } = props;

  const {
    hello,
    name,
    label,
    miniDescription,
    longDiscription: { p1, p2, p3, p4, p5, skills },
  } = author(params.lang);

  return (
    <div className="flex flex-col gap-8 max-w-4xl mx-auto">
      <Author>
        <Image
          src={person}
          width={200}
          height={300}
          alt=""
          className="bg-primary-gray rounded-2xl"
        />
        <About>
          <Hello>
            <HelloLine /> {hello}
          </Hello>
          <div>
            <Title>{name}</Title>
            <SubTitle>{label}</SubTitle>
          </div>
          <Bio>{miniDescription}</Bio>
        </About>
      </Author>
      <div className="text-primary-gray leading-7 rtl:font-light ltr:text-sm">
        <p>{p1}</p>
        <p>{p2}</p>
        <p>{p3}</p>
        <p>{p4}</p>

        <b>{skills.title}</b>
        <ul className="list-disc list-inside mb-5">
          {skills.list.map((item, index) => (
            <li key={`skill-${index}`}>{item}</li>
          ))}
        </ul>
        <p>{p5}</p>
      </div>
    </div>
  );
}

const Author = tw.main`flex flex-col md:flex-row items-center gap-8 m-auto`;
const About = tw.div`flex flex-col gap-3`;
const Hello = tw.div`flex items-center gap-2`;
const HelloLine = tw.div`bg-primary-green w-4 h-0.5 rounded-full`;
const Title = tw.h2`text-lg`;
const SubTitle = tw.h3`text-xs text-primary-gray`;
const Bio = tw.p`text-primary-gray  leading-7`;
